src/infrastructure/routes/actions.py, src/infrastructure/routes/web.py
Ce fix corrigera le problème de CORS côté web sur l'api /actions/{id_action}.
- Une route similaire a la route de base a été rajouté dans le fichier de route web.py
- Nous avons ajouté le label 'v1' au niveau de la route pour ne pas avoir deux routes identiques
=> fix: utiliser PUT et PATCH pour le statut d une action

src/application/queries/query-models/rendez-vous.query-models.ts, src/infrastructure/repositories/mappers/rendez-vous.mappers.ts, test/fixtures/rendez-vous.fixture.ts, test/infrastructure/repositories/rendez-vous-sql.repository.test.ts
Ajout des jeunes et conseillers sur les routes rdvs.
[PR équivalente web](https://github.com/SocialGouv/pass-emploi-web/pull/148)
=> fix: ajout du jeune et conseiller sur les routes des rdvs

src/application/commands/create-rendez-vous.command.handler.ts, src/application/queries/query-models/rendez-vous.query-models.ts, src/domain/rendez-vous.ts, src/infrastructure/repositories/mappers/rendez-vous.mappers.ts, src/infrastructure/sequelize/migrations/20220407110000-mettre-le-createur-dans-les-rdv.js, src/infrastructure/sequelize/models/rendez-vous.sql-model.ts, test/application/commands/create-rendez-vous.command.handler.test.ts, test/domain/rendez-vous.test.ts, test/fixtures/rendez-vous.fixture.ts, test/fixtures/sql-models/rendez-vous.sql-model.ts, test/infrastructure/repositories/rendez-vous-sql.repository.test.ts
Créateur du RDV stocké dans la base.
Non testé.
La migration arrive dans un futur commit.
=> createur rdv stocké dans la base

src/infrastructure/routes/validation/rendez-vous.inputs.ts
Rend commentaire en optionnel dans la création de rdv
Fixe l'envoie du formulaire de création de rdv
=> fix(us-538): Correction champ commentaire en optionnel création rdv

src/application/queries/get-rendez-vous-conseiller.query.handler.ts, test/application/queries/get-rendez-vous-conseiller.query.handler.test.ts
La requête SQL passe en localhost avec un petit jeu de données et des paramètres en dur.
Reste l'intégration au query handler.
=> wip: fix requete sql rdv conseiller

src/application/queries/get-actions-by-jeune.query.handler.db.ts, src/infrastructure/routes/jeunes.controller.ts, test/application/queries/get-actions-by-jeune.query.handler.db.test.ts, test/application/queries/get-jeune-home-actions.query.handler.test.ts, test/infrastructure/routes/jeunes.controller.test.ts
=> feat: metadata de la liste des actions

src/app.module.ts, src/application/commands/transferer-jeunes-conseiller.command.handler.ts, src/domain/jeune/jeune.ts, src/domain/rendez-vous.ts, src/infrastructure/repositories/rendez-vous/animation-collective-sql.repository.db.ts, src/infrastructure/repositories/rendez-vous/rendez-vous-sql.repository.db.ts, test/application/commands/transferer-jeunes-conseiller.command.handler.test.ts, test/domain/rendez-vous.test.ts, test/fixtures/rendez-vous.fixture.ts, test/infrastructure/repositories/animation-collective-sql.repository.db.test.ts, test/infrastructure/repositories/rendez-vous-sql.repository.db.test.ts
=> feat(1151): desinscrire des AC lors des transferts

src/application/commands/transferer-jeunes-conseiller.command.handler.ts, src/domain/conseiller/liste-de-diffusion.ts, src/infrastructure/repositories/conseiller/liste-de-diffusion-sql.repository.db.ts, test/application/commands/transferer-jeunes-conseiller.command.handler.test.ts, test/infrastructure/repositories/conseiller/liste-de-diffusion-sql.repository.db.test.ts
=> feat(1229): Nettoie liste diffusion quand reaffectation definitive

src/app.module.ts, src/application/commands/envoyer-message-groupe.command.handler.ts, src/domain/chat.ts, src/infrastructure/clients/dto/firebase.dto.ts, src/infrastructure/clients/firebase-client.ts, src/infrastructure/repositories/chat-firebase.repository.ts, src/infrastructure/routes/messages.controller.ts, src/infrastructure/routes/validation/messages.input.ts, test/application/commands/envoyer-message-groupe.command.handler.test.ts, test/infrastructure/routes/messages.controller.test.ts
=> feat(1274): Envoyer message groupé

src/application/authorizers/authorize-conseiller-agence.ts, src/application/queries/rendez-vous/get-detail-rendez-vous.query.handler.db.ts, test/application/authorizers/authorize-conseiller-agence.test.ts, test/application/queries/rendez-vous/get-detail-rendez-vous.query.handler.db.test.ts
fix : sur la route /rendezvous/:rdv ( GetDetailRendezVousQueryHandler ) , autorise le conseiller du jeune ou le conseiller des meme agence a avoir acces a la consulation des rdv d'un jeune
=> fix:  fix authorizer get detail rendez vous

src/app.module.ts, src/application/commands/update-rendez-vous.command.handler.ts, src/building-blocks/types/domain-error.ts, src/domain/rendez-vous/rendez-vous.ts, src/infrastructure/routes/failure.handler.ts, test/application/commands/create-rendez-vous.command.handler.test.ts, test/application/commands/update-rendez-vous.command.handler.test.ts, test/domain/rendez-vous/rendez-vous.test.ts
(cherry picked from commit 297c1c6083f514a10ff24d839da4d78de6241f66)
=> feat: verification de la date du rdv a sa creation

src/application/jobs/analytics/vues/3-1-vue-fonctionnalites.ts
=> Fix lack of match on type_utilisateur

src/app.module.ts, src/application/queries/get-cv-pole-emploi.query.handler.ts, src/application/queries/query-models/jeunes.pole-emploi.query-model.ts, src/infrastructure/clients/dto/pole-emploi.dto.ts, src/infrastructure/clients/pole-emploi-partenaire-client.ts, src/infrastructure/routes/jeunes.pole-emploi.controller.ts, test/application/queries/get-cv-pole-emploi.query.handler.test.ts, test/infrastructure/clients/pole-emploi-partenaire-client.test.ts, test/infrastructure/routes/jeunes.pole-emploi.controller.test.ts
Penser à Terraform le nouveau scope sur Keycloak pour la recette.
=> feat(cv): retourne la liste

src/application/commands/milo/update-session-milo.command.handler.ts, src/domain/milo/session.milo.ts, src/infrastructure/repositories/milo/session-milo-http-sql.repository.db.ts, src/infrastructure/routes/validation/conseiller-milo.inputs.ts, test/application/commands/milo/update-session-milo.command.handler.test.ts, test/infrastructure/routes/conseillers.milo.controller.test.ts
:warning: À merger après #1140
=> feat: split types and add Inscription.Statut.PRESENT

src/app.module.ts, src/application/commands/milo/emargement-session-milo.command.handler.ts, src/building-blocks/types/domain-error.ts, src/domain/milo/session.milo.ts, src/infrastructure/clients/milo-client.ts, src/infrastructure/repositories/milo/session-milo-http-sql.repository.db.ts, src/infrastructure/routes/conseillers.milo.controller.ts, src/infrastructure/routes/validation/conseiller-milo.inputs.ts, test/application/commands/milo/emargement-session-milo.command.handler.test.ts, test/application/commands/milo/update-session-milo.command.handler.test.ts, test/domain/milo/session.milo.test.ts, test/infrastructure/clients/milo-client.test.ts, test/infrastructure/repositories/milo/session-milo-http-sql.repository.db.test.ts
Ben je crois que c'est tout bong :)
Il reste 2 bugs Sonar suite à l'usage de notre `sort()` : "Provide a compare function to avoid sorting elements alphabetically."
Mais en vrai, c'est exactement ce que l'on veut, et on a un test qui couvre, donc je vous laisse décider de le mettre en "won't fix" ou de rajouter un param à la méthode.
A bientôt les loulous, à plus sur le vélib,
=> feat(session): 157 - Émargement et clôture API Clore une session

src/app.module.ts, src/application/authorizers/conseiller-inter-structure-milo-authorizer.ts, src/application/queries/milo/get-sessions-jeune.milo.query.handler.db.ts, src/domain/milo/jeune.milo.ts, src/infrastructure/repositories/jeune/jeune-milo-http-sql.repository.db.ts, src/infrastructure/routes/jeunes.milo.controller.ts, test/application/authorizers/conseiller-inter-structure-milo-authorizer.test.ts, test/application/queries/milo/get-sessions-jeune.milo.query.handler.db.test.ts, test/infrastructure/repositories/jeune/jeune-milo-http-sql.repository.db.test.ts
Ouverture de la route `GET /jeunes/milo/{id}/sessions` au conseiller.
=> feat: permet conseiller récupérer sessions jeune

src/app.module.ts, src/application/jobs/suivre-file-evenements-milo.job.handler.ts, src/application/jobs/traiter-evenement-milo.job.handler.ts, src/domain/milo/rendez-vous.milo.ts, src/domain/notification/notification.ts, src/domain/planificateur.ts, src/infrastructure/repositories/dto/milo.dto.ts, src/infrastructure/repositories/rendez-vous/rendez-vous-milo-http.repository.ts, test/application/jobs/suivre-file-evenements-milo.job.handler.test.ts, test/application/jobs/traiter-evenement-milo.job.handler.test.ts, test/domain/milo/rendez-vous.milo.test.ts, test/fixtures/partenaire.fixture.ts, test/infrastructure/repositories/rendez-vous/rendez-vous-milo-http.repository.test.ts
=> Décommissionement batch intances sessions + notifs

src/infrastructure/routes/etablissements.controller.ts, src/infrastructure/routes/structures-milo.controller.ts, src/infrastructure/routes/validation/etablissements.inputs.ts, src/infrastructure/routes/validation/structures-milo.inputs.ts, test/infrastructure/routes/structures-milo.controller.test.ts
Refaire la route POST cloture /etablissements/animation-collective/cloturer en /structures-milo/animations-collectives/cloturer
=> Route structure milo animations collectives

src/domain/action/action.ts, test/application/commands/milo/qualifier-action.command.handler.test.ts, test/application/commands/milo/qualifier-actions-milo.command.handler.test.ts, test/domain/action/action.test.ts
https://trello.com/c/IgbPIokw/2263-correction-des-r%C3%A8gles-de-calcul-automatique-des-dates-cr%C3%A9ation-d%C3%A9ch%C3%A9ance-et-fin-r%C3%A9elle
=> fix: corrige date debut et fin action

src/application/commands/archiver-jeune.command.handler.ts, src/domain/archive-jeune.ts, src/infrastructure/clients/firebase-client.ts, src/infrastructure/repositories/archive-jeune-sql.repository.db.ts, test/infrastructure/repositories/archive-jeune-sql.repository.db.test.ts
(cherry picked from commit a40f7c3b6d606c10681fd1e2d60b88fa3cc2ff1a)
=> feat: ajoute historique message archive beneficiaire

src/application/jobs/analytics/vues/3-1-vue-fonctionnalites.ts
Pour éviter de compter 2 fois les actions dupliquées dans analytics-fonctionnalités
=> fix(analytics): exclusion duplication action des ae

src/application/jobs/suivre-file-evenements-milo.job.handler.ts, src/application/jobs/traiter-evenement-milo.job.handler.ts, src/domain/milo/evenement.milo.ts, src/infrastructure/repositories/dto/milo.dto.ts, src/infrastructure/repositories/milo/evenement-milo-http.repository.ts, src/infrastructure/repositories/milo/rendez-vous-milo-http.repository.ts, test/application/jobs/suivre-file-evenements-milo.job.handler.test.ts, test/application/jobs/traiter-evenement-milo.job.handler.test.ts, test/infrastructure/repositories/milo/rendez-vous-milo-http.repository.test.ts
https://trello.com/c/GbT26D8d/2522-investigation-les-b%C3%A9n%C3%A9ficiaires-trouvent-quils-re%C3%A7oivent-trop-de-notifications-lorsquils-sont-inscrits-%C3%A0-une-session-i-milo
https://trello.com/c/0pHFSdJc/2753-rdv-individuel-i-milo-afficher-le-commentaire-et-le-lieu
=> feat(event-milo): maj dto + ajout lieu + gestion doublons

src/application/queries/get-indicateurs-pour-conseiller.query.handler.db.ts, src/application/queries/get-jeune-home-agenda.query.handler.db.ts, src/application/queries/milo/get-accueil-jeune-milo.query.handler.db.ts, src/application/queries/milo/get-mon-suivi-jeune.milo.query.handler.db.ts, src/application/queries/milo/get-sessions-jeune.milo.query.handler.db.ts, src/application/queries/query-getters/milo/get-sessions-jeune.milo.query.getter.db.ts, src/application/queries/query-mappers/milo.mappers.ts, src/domain/milo/session.milo.ts, src/infrastructure/routes/conseillers.controller.ts, src/utils/date-service.ts, test/application/queries/get-indicateurs-pour-conseiller.query.handler.db.test.ts, test/application/queries/get-jeune-home-agenda.query.handler.db.test.ts, test/application/queries/milo/get-accueil-jeune-milo.query.handler.db.test.ts, test/application/queries/milo/get-mon-suivi-jeune.milo.query.handler.db.test.ts, test/application/queries/milo/get-sessions-jeune.milo.query.handler.db.test.ts, test/application/queries/query-getters/milo/get-sessions-jeune.milo.query.getter.db.test.ts, test/infrastructure/routes/conseillers.controller.test.ts
- rajoute les REFUS_JEUNE aux sessions de la semaine dans les indicateurs du portefeuille
- rajoute les sessions au indicateurs de la fiche bénéficiaire
=> Corrige incohérences compteurs sessions

src/domain/demarche.ts, test/domain/demarche.test.ts
This reverts commit 63a7c2a37ebf3cff51acd25a6f4786772a4079a6.
=> Reapply "feat: mettre demarche en realisee quand la date de fin est au passé"
